language: python
python:
- 3.5
before_install:
  - pip install coveralls
  - pip install flake8
  - pip install pytest

script:
  - flake8 oshino
  - coverage run --source oshino -m py.test

after_success:
  - coveralls
