language: python
python:
- 3.5
- 3.6

services:
  - docker

install:
  - python setup.py install
  - pip install -r requirements/test.txt

script:
  - flake8 oshino
  - coverage run --source oshino -m py.test

after_success:
  - coveralls
