language: python
python:
- 3.5

install:
  - pip install -r requirements/release.txt
  - pip install -r requirements/test.txt

script:
  - flake8 oshino
  - coverage run --source oshino -m py.test

after_success:
  - coveralls
