version: "3"

services:
  oshino:
    build:
      context: .
      dockerfile: compose/Dockerfile
  oshino-query:
    build:
      context: .
      dockerfile: compose/Dockerfile
    command: ["/usr/local/bin/oshino-admin", "query", "'tagged = \"healthcheck\"'"]
    depends_on:
      - oshino
      - riemann
  riemann:
    image: "rlister/riemann"
